"""
Facebook Graph API v25.0 wrapper for the FieldKit photo-video agent.

Handles OAuth token exchange and video upload to a Facebook Page.

Exception hierarchy:
  FacebookTokenError(RuntimeError)  — token invalid/expired (error code 190); skip retries
  FacebookUploadError(RuntimeError) — all other failures; retry eligible

FB_APP_SECRET is used only in exchange_code_for_token and exchange_for_long_lived_token.
It must never be logged or appear in upload_facebook.py (cron path).
"""

import logging
from pathlib import Path
from urllib.parse import urlencode

import requests

logger = logging.getLogger(__name__)

_GRAPH_BASE = "https://graph.facebook.com/v25.0"
_OAUTH_DIALOG = "https://www.facebook.com/dialog/oauth"


class FacebookTokenError(RuntimeError):
    """Raised when the Facebook Page access token is invalid or expired (error code 190).

    The caller should not retry — the token must be renewed via generate_auth_link.py.
    """


class FacebookUploadError(RuntimeError):
    """Raised on all other Facebook API or network failures.

    The caller may retry according to the configured retry policy.
    """


def build_auth_url(app_id: str, redirect_uri: str, scopes: list[str], state_token: str) -> str:
    """Return the Facebook OAuth dialog URL for the given scopes.

    The state_token should be a random value generated by the caller for CSRF protection.
    """
    params = {
        "client_id": app_id,
        "redirect_uri": redirect_uri,
        "scope": ",".join(scopes),
        "state": state_token,
        "response_type": "code",
    }
    return f"{_OAUTH_DIALOG}?{urlencode(params)}"


def exchange_code_for_token(code: str, app_id: str, app_secret: str, redirect_uri: str) -> str:
    """Exchange an OAuth authorization code for a short-lived user access token.

    Raises FacebookUploadError on HTTP error, network failure, or FB API error.
    """
    try:
        resp = requests.post(
            f"{_GRAPH_BASE}/oauth/access_token",
            data={
                "client_id": app_id,
                "client_secret": app_secret,
                "redirect_uri": redirect_uri,
                "code": code,
            },
            timeout=30,
        )
    except requests.exceptions.RequestException as exc:
        raise FacebookUploadError(f"Token exchange request failed: {exc}") from exc

    if not resp.ok:
        raise FacebookUploadError(f"Token exchange failed: HTTP {resp.status_code}")

    data = resp.json()
    if "error" in data:
        raise FacebookUploadError(f"Token exchange error: {data['error']}")
    return data["access_token"]


def exchange_for_long_lived_token(short_token: str, app_id: str, app_secret: str) -> str:
    """Exchange a short-lived user token for a long-lived one (60-day expiry).

    Raises FacebookUploadError on failure.
    """
    try:
        resp = requests.get(
            f"{_GRAPH_BASE}/oauth/access_token",
            params={
                "grant_type": "fb_exchange_token",
                "client_id": app_id,
                "client_secret": app_secret,
                "fb_exchange_token": short_token,
            },
            timeout=30,
        )
    except requests.exceptions.RequestException as exc:
        raise FacebookUploadError(f"Long-lived token exchange request failed: {exc}") from exc

    if not resp.ok:
        raise FacebookUploadError(f"Long-lived token exchange failed: HTTP {resp.status_code}")

    data = resp.json()
    if "error" in data:
        raise FacebookUploadError(f"Long-lived token exchange error: {data['error']}")
    return data["access_token"]


def get_page_access_token(long_user_token: str, page_id: str) -> str:
    """Return the permanent Page access token for page_id from the user's /me/accounts.

    Raises FacebookUploadError on HTTP error, network failure, or page not found.
    """
    try:
        resp = requests.get(
            f"{_GRAPH_BASE}/me/accounts",
            params={"access_token": long_user_token},
            timeout=30,
        )
    except requests.exceptions.RequestException as exc:
        raise FacebookUploadError(f"Failed to fetch page accounts: {exc}") from exc

    if not resp.ok:
        raise FacebookUploadError(f"Failed to fetch page accounts: HTTP {resp.status_code}")

    data = resp.json()
    if "error" in data:
        raise FacebookUploadError(f"Graph API error fetching pages: {data['error']}")

    for page in data.get("data", []):
        if page.get("id") == page_id:
            return page["access_token"]

    raise FacebookUploadError(f"Page {page_id!r} not found in user's accounts")


def delete_post(page_access_token: str, post_id: str) -> None:
    """Delete a Facebook post by ID.

    Raises:
        FacebookUploadError — on HTTP error, network failure, or any Graph API error
            including code 100 ("post not found"). Callers that want to treat code 100
            as a non-fatal warning should catch FacebookUploadError explicitly.
    """
    url = f"{_GRAPH_BASE}/{post_id}"
    try:
        resp = requests.delete(
            url,
            params={"access_token": page_access_token},
            timeout=30,
        )
    except requests.exceptions.RequestException as exc:
        raise FacebookUploadError(f"Post delete request failed: {exc}") from exc

    try:
        data = resp.json()
    except Exception:
        data = {}

    error = data.get("error") if isinstance(data, dict) else None
    if error:
        code = error.get("code") if isinstance(error, dict) else None
        msg = error.get("message", "") if isinstance(error, dict) else str(error)
        raise FacebookUploadError(f"Facebook API error {code} deleting post {post_id}: {msg}")

    if not resp.ok:
        raise FacebookUploadError(f"Post delete failed: HTTP {resp.status_code}")

    logger.info("delete_post: post_id=%s", post_id)


def upload_video(page_access_token: str, page_id: str, video_path) -> str:
    """Upload a video file to a Facebook Page. Returns the Facebook post ID.

    Uses non-resumable multipart POST (suitable for files < 100 MB).

    Raises:
        FacebookTokenError — if the Graph API returns error code 190 (token invalid/expired).
        FacebookUploadError — on all other API errors, HTTP failures, or network errors.
    """
    url = f"{_GRAPH_BASE}/{page_id}/videos"
    video_path = Path(video_path)

    try:
        with open(video_path, "rb") as f:
            resp = requests.post(
                url,
                data={"access_token": page_access_token},
                files={"source": f},
                timeout=60,
            )
    except requests.exceptions.RequestException as exc:
        raise FacebookUploadError(f"Video upload request failed: {exc}") from exc

    try:
        data = resp.json()
    except Exception:
        data = {}

    # Facebook may return a 2xx HTTP status with an error body (e.g., token expiry).
    error = data.get("error") if isinstance(data, dict) else None
    if error:
        code = error.get("code") if isinstance(error, dict) else None
        msg = error.get("message", "") if isinstance(error, dict) else str(error)
        if code == 190:
            raise FacebookTokenError(f"Facebook token invalid/expired: {msg}")
        raise FacebookUploadError(f"Facebook API error {code}: {msg}")

    if not resp.ok:
        raise FacebookUploadError(f"Upload failed: HTTP {resp.status_code}")

    try:
        return data["id"]
    except (KeyError, TypeError) as exc:
        raise FacebookUploadError(
            f"Upload response missing 'id' field: {exc} — response: {data!r}"
        ) from exc
